name: Calculate meeting times

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 1,2,3"
    - cron: "17 0 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get data from Clockify
      id: report
      env:
        CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
      run: |
        TIMEREPORT=$(python report.py)
        TIMEREPORT="${TIMEREPORT//'%'/'%25'}"
        TIMEREPORT="${TIMEREPORT//$'\n'/'%0A'}"
        TIMEREPORT="${TIMEREPORT//$'\r'/'%0D'}"
        echo "::set-output name=time_spent::```$TIMEREPORT```"
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: ${{ steps.report.outputs.time_spent }}
        SLACK_TITLE: TimeSpender
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
